export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as NavBar } from './NavBar'
export { default as FormLogin } from './FormLogin'
export { default as FormSignUp } from './FormSignUp'
export { default as Slider } from './Slider'
export { default as Card } from './Card'
